spring:
  application:
    name: PlaygroundMath
  datasource:
    url: jdbc:mysql://mysql:3306/playgroundmath
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true  # <-- This prints out the SQL
  mail:
    host: smtp.gmail.com
    port: 587
    username: "zivojin.2001davidovic@gmail.com"
    password: "mcqr qvph saks dbuc"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  key: ljkasdafjklhadlsjfhasdkjhfekjhljkasdafjklhadlsjfhasdkjhfekjh
  access-token-expiration: 36000000
  refresh-token-expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
   # org.hibernate.SQL: DEBUG  # <-- This prints the actual SQL statements
   # org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # <-- This prints parameter bindings
